# a configuration file for the project
[lsmt]
LSM_SUM_MEMTABLE_SIZE = 67108864 # 64 * 1024 * 1024
LSM_PER_MEMTABLE_SIZE = 4194304  #  4 * 1024 * 1024
LSM_SST_LEVEL_RATIO   = 4
LSM_BLOCK_SIZE        = 32768    # 32 * 1024
LSM_BLOCK_CACHE_SIZE  = 1024
LSM_BLOCK_CACHE_LRUK  = 8

[bloom_filter]
BLOOM_FILTER_EXPECTED_ELEMENTS   = 65536
BLOOM_FILTER_FALSE_POSITIVE_RATE = 0.1
